faq_questions = [
    "Tell me about Vaagdevi College of Engineering",
    "What undergraduate programs does Vaagdevi College offer or courses offered?",
    "How do I apply for B.Tech programs?",
    "What entrance exams are accepted for admission?",
    "What's the admission process for international students?",
    "Where can I find the academic calendar?",
    "What scholarship opportunities are available?",
    "How do I apply for financial aid?",
    "Are there scholarships for postgraduate students?",
    "What hostel facilities are available?",
    "What sports facilities does the campus have?",
    "Are there medical facilities on campus?",
    "What transportation options are available?",
    "What's the student-faculty ratio?",
    "What research opportunities are available?",
    "How are labs equipped for practical learning?",
    "Does the college offer study abroad programs?",
    "What's the recent placement record?",
    "Which companies regularly recruit here?",
    "What career support services are offered?",
    "What's the average salary package?",
    "What extracurricular activities are available?",
    "How does the college support mental health?",
    "What security measures are in place?",
    "How does the incubation center support startups?",
    "What language training programs are available?",
    "Are there personality development workshops?",
    "How do I contact specific departments?",
    "What's the grievance redressal process?",
    "Where can I find exam schedules?",
    "What accreditations does the college hold?",
    "What makes Vaagdevi unique among engineering colleges?",
    "How does the college promote innovation?",
    "Can I visit the campus before admission?",
    "Are there any internship opportunities for students?",
    "What are the placement statistics for the last few years?",
    "What sports facilities are available?"
]

faq_answers = [
    "Vaagdevi College of Engineering is an esteemed institution offering quality technical education with a focus on innovation, research, and industry collaborations. More details: https://www.vaagdevi.edu.in/.",
    "Vaagdevi offers B.Tech in Computer Science, Electronics, Mechanical, Civil, and Electrical Engineering. Details: https://www.vaagdevi.edu.in/programs",
    "Apply online through TS EAMCET counseling with required documents. Portal: https://www.vaagdevi.edu.in/admissions",
    "We accept TS EAMCET for B.Tech, TS ICET for MBA/MCA, and GATE for M.Tech. Full list: https://www.vaagdevi.edu.in/exams",
    "International students apply through the International Office with equivalent qualifications. Email: international@vaagdevi.edu.in",
    "Academic calendar with important dates is available at https://www.vaagdevi.edu.in/academic-calendar",
    "Merit-based (up to 100% fee waiver) and need-based scholarships available. Details: https://www.vaagdevi.edu.in/scholarships",
    "Submit financial aid application with supporting documents to the Financial Assistance Office before deadlines",
    "Yes, PG students can apply for AICTE scholarships and research assistantships. Criteria: https://www.vaagdevi.edu.in/pg-scholarships",
    "Separate AC/non-AC hostels with WiFi, 24/7 security, and mess facilities. Virtual tour: https://www.vaagdevi.edu.in/hostels",
    "Olympic-size swimming pool, cricket ground, basketball courts, and indoor stadium. Facilities list: https://www.vaagdevi.edu.in/sports",
    "24/7 medical center with resident doctor and ambulance service. Health portal: https://www.vaagdevi.edu.in/health",
    "College buses cover all major routes in Warangal. Route map: https://www.vaagdevi.edu.in/transport",
    "Our 15:1 ratio ensures personalized attention. Faculty profiles: https://www.vaagdevi.edu.in/faculty",
    "Undergraduate research programs with ₹50,000 grants available. Research portal: https://research.vaagdevi.edu.in",
    "Labs feature Industry 4.0 equipment including 3D printers and IoT development kits. Lab list: https://www.vaagdevi.edu.in/labs",
    "Semester exchange programs with 20+ international universities. Partners: https://www.vaagdevi.edu.in/global-programs",
    "92% placement rate in 2023 with 780+ offers. Placement report: https://www.vaagdevi.edu.in/placements",
    "Top recruiters include Microsoft, Amazon, TCS, and L&T. Complete list: https://www.vaagdevi.edu.in/recruiters",
    "Career services offers resume building, mock interviews, and industry mentorship. Schedule: https://careers.vaagdevi.edu.in",
    "2023 average package: ₹6.2 LPA, highest: ₹42 LPA. Details: https://www.vaagdevi.edu.in/placement-stats",
    "100+ clubs including Robotics, AI Club, and Cultural Society. Activities calendar: https://www.vaagdevi.edu.in/clubs",
    "Free counseling services and stress management workshops through Student Wellness Center",
    "Campus-wide CCTV surveillance, biometric entry, and emergency response teams. Safety guide: https://www.vaagdevi.edu.in/safety",
    "VIBA incubation center provides ₹5 lakh seed funding and mentorship for student startups. Apply: https://viba.vaagdevi.edu.in",
    "IELTS/TOEFL training programs with mock tests. Language lab schedule: https://www.vaagdevi.edu.in/language-lab",
    "Weekly soft skills workshops and leadership development programs. Schedule: https://www.vaagdevi.edu.in/workshops",
    "Department contacts available at https://www.vaagdevi.edu.in/departments",
    "Submit grievances online through portal: https://grievance.vaagdevi.edu.in (resolution within 72 hours)",
    "Exam schedules published on https://exams.vaagdevi.edu.in 3 weeks prior to tests",
    "NAAC 'A++' accredited, NBA accredited programs, ISO 9001:2015 certified",
    "Industry-integrated curriculum with 40+ corporate partnerships and 70-acre innovation campus",
    "Through ₹10 crore innovation fund, annual hackathons, and 35 patents filed by students",
    "Yes, prospective students can schedule a campus tour before admission by contacting the admissions office. Booking details: https://www.vaagdevi.edu.in/.",
    "Internship opportunities are available through industry collaborations, research projects, and placement support. Internship details: https://www.vaagdevi.edu.in/.",
    "Vaagdevi College has a strong placement record, with students placed in companies like TCS, Infosys, and Wipro. Placement statistics: https://www.vaagdevi.edu.in/.",
    "The college has excellent sports facilities, including basketball courts, cricket grounds, indoor badminton courts, table tennis, and a gymnasium. Sports details: https://www.vaagdevi.edu.in/."
]